### ISSUE TITLE
Fix README.md

### ISSUE THREAD

**Issue by henriquebonadio** [yaal-coop/scim2-client#16]
Fix the Example usage on README.md (just a little typo but it took me some time to realize it)

from:
`from scim2_models import User, EnterpriseUserUser, Group, Error`
to:
`from scim2_models import User, EnterpriseUser, Group, Error`

and also here (i think):
from:
`user = scim.query(User, "2819c223-7f76-453a-919d-413861904646")`
to:
`user = scim.query(User[EnterpriseUser], "2819c223-7f76-453a-919d-413861904646")`

**Comment by azmeuk** [comment]
Hi. Thank you for your report.
Would you like to open a PR?

**Comment by henriquebonadio** [comment]
https://github.com/yaal-coop/scim2-client/pull/17
