### ISSUE TITLE
Is there a way to pass Bearer token?

### ISSUE THREAD

**Issue by fflorent** [yaal-coop/scim2-client#21]
We can pass the option `--token` to [scim2-test](https://github.com/yaal-coop/scim2-tester), but such option does not seem exist for scim2-client.

**Comment by azmeuk** [comment]
The network related parameters are delegated to [httpx](https://www.python-httpx.org/), as shown in the README, any header can be passed with the `headers` parameter:

https://github.com/yaal-coop/scim2-client/blob/41d575fb2254460e9c44c7bcb7d6f853e8319dbd/README.md?plain=1#L34

**Comment by fflorent** [comment]
Sorry, I mixed this project with `scim-cli` which in their README describe the `--headers` options.
